default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: farma_alg_development

test:
  <<: *default
  database: farma_alg_test

production:
  <<: *default
  database: farma_alg_production
  username: farma_alg
  password: <%= ENV['FARMA_ALG_DATABASE_PASSWORD'] %>